### ISSUE TITLE
Implement ability to pause and resume recording...

### ISSUE THREAD

**Issue by rpbarbati** [sohwendy/Robotcorder#6]
Often during test recording, the user has to refer to some other document or page or other resource.  Doing so basically messes up the test being recorded.  

It would be very useful to be able to pause the recorder prior to departing the page and resume when returning.  

The plugin should not attempt to identify when the user leaves, but rather provide buttons for pause and resume during recording.

**Comment by sohwendy** [comment]
Thanks for the suggestion. I will look into how to incorporate a pause feature.

**Comment by sohwendy** [comment]
Robotcorder supports pause/resume feature.
You can get the latest version 0.3.0 from the web store.

**Comment by rpbarbati** [comment]
You are awesome - when I put in the suggestion I figured it would just sit there for years, but lo and behold, you are on it!!  Great job!
